/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: lusanche <marvin@42.fr>                    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2019/10/16 21:08:55 by lusanche          #+#    #+#             */
/*   Updated: 2019/11/01 21:29:04 by lusanche         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "ft_printf.h"
#include <stdio.h>

int		main(void)
{
	char					ch = -128;							//hh
	short					sh = -32768;						//h
	int						in = -2147483647;					// no flag
	long					lon = -9223372036854775807;			//l
	long long				lonlon = -9223372036854775807;		//ll	
	unsigned char			uch = 255;							//hh
	unsigned short			ush = 65535;						//h
	unsigned int			uin = 4294967295;					// no flag
	unsigned long			ulon = 9223372036854775807;			//l
	unsigned long long		ulonlon = 9223372036854775807;		//ll
	void					*p = "pointer";
	void					*p1 = &in;

	setbuf(stdout, NULL);
/*	printf("[c] -------------------------------------------------------------\n");
	printf("%c\n", 42);
	printf("%-c\n", 42);
	printf("%20c\n", 42);
	printf("[s] -----------------------------------------------------------\n");
	printf("%s\n", "silicon valley");
	printf("%-s\n", "silicon valley");
	printf("%20s\n", "silicon valley");
	printf("%.3s\n", "silicon valley");
	printf("[p] -------------------------------------------------------------\n");
	printf("%p\n", p);
	printf("%-p\n", p);
	printf("%20p\n", p);
	printf("[d] -------------------------------------------------------------\n");
	printf("%d\n", in);
	printf("%hhd\n", ch);
	printf("%hd\n", sh);
	printf("%ld\n", lon);
	printf("%lld\n", lonlon);
	printf("%0d\n", 777);
	printf("%-d\n", 777);
	printf("% d\n", 777);
	printf("%+d\n", 777);
	printf("%10d\n", 777);
	printf("%.5d\n", 777);
	printf("[o] -----------------------------------------------------------\n");
	printf("%o\n", 112);		// dec 112 = oct 160
	printf("%o\n", 160);		// dec 160 = oct 240
	printf("%o\n", 'p');		// 'p' = dec 112 = oct 160
	printf("%hho\n", uch);
	printf("%ho\n", ush);
	printf("%o\n", uin);
	printf("%lo\n", ulon);
	printf("%llo\n", ulonlon);
	printf("%#o\n", 112);
	printf("%0o\n", 112);
	printf("%-o\n", 112);
	printf("%10o\n", 112);
	printf("%.5o\n", 112);
	printf("[u] -----------------------------------------------------------\n");
	printf("%u\n", 2010);
	printf("%hhu\n", uch);
	printf("%hu\n", ush);
	printf("%u\n", uin);
	printf("%lu\n", ulon);
	printf("%llu\n", ulonlon);
	printf("%0u\n", uin);
	printf("%-u\n", uin);
	printf("%30u\n", uin);
	printf("%.30u\n", uin);
	printf("[x] -----------------------------------------------------------\n");
	printf("%x\n", 2010);
	printf("%hhx\n", uch);
	printf("%hx\n", ush);
	printf("%x\n", uin);
	printf("%lx\n", ulon);
	printf("%llx\n", ulonlon);
	printf("%#x\n", 2010);
	printf("%0x\n", 2010);
	printf("%-x\n", 2010);
	printf("%10x\n", 2010);
	printf("%.5x\n", 2010);
	printf("[X] -----------------------------------------------------------\n");
	printf("%X\n", 2010);
	printf("%hhX\n", uch);
	printf("%hX\n", ush);
	printf("%X\n", uin);
	printf("%lX\n", ulon);
	printf("%llX\n", ulonlon);
	printf("%#X\n", 2010);
	printf("%0X\n", 2010);
	printf("%-X\n", 2010);
	printf("%10X\n", 2010);
	printf("%.5X\n", 2010);
	printf("[f] -----------------------------------------------------------\n");
	printf("%f\n", 3.1416);
	printf("%lf\n", (double) 3.1416);
	printf("%Lf\n", (long double) 3.1416);
	printf("%#.f\n", 3.1);
	printf("%0f\n", 3.1416);
	printf("%-f\n", 3.1416);
	printf("% f\n", 3.1416);
	printf("%+f\n", 3.1416);
	printf("%20f\n", 3.1416);
	printf("%.20f\n", 3.1416);
	printf("[%%] -----------------------------------------------------------\n");
	printf("%%\n");
	printf("%%%d\n", 35);
	printf("%c%%%d\n", 'h', 35);
	printf("%#%\n");
	printf("%0%\n");
	printf("%-%\n");
	printf("% %\n");
	printf("%+%\n");
	printf("%20%\n");
	printf("%.0%\n");
	printf("[\\] -----------------------------------------------------------\n");
	printf("%\"\n", 128);
	printf("%20\"\n", 128);
	printf("%020\"\n", 128);
	printf("%-20\"\n", 128);
	printf("[other] -------------------------------------------------------\n");
	printf("%m\n", 128);
	printf("%20m\n", 128);
	printf("%020m\n", 128);
	printf("%-20m\n", 128);
	printf("[empty] --------------------------------------------------------\n");
	printf("%-20", 128);
	printf("%-20hh", 128);
	printf("%", 128);*/
//fflush(stdout);
	printf("[d int] --------------------------------------------------\n");
	printf("%#0- +30.20lllhhhLlLhhhlll.20+30 -0#dcsphola\n", 20);
	ft_printf("%#0- +30.20lllhhhLlLhhhlll.20+30 -0#dcsphola\n", 20);
	printf("%#0- +40.30d\n", in);
	ft_printf("%#0- +40.30d\n", in);
	printf("%#0 +40.30d\n", in);
	ft_printf("%#0 +40.30d\n", in);
	printf("%#- +40.30d\n", in);
	ft_printf("%#- +40.30d\n", in);
	printf("%# +.30d\n", in);
	ft_printf("%# +.30d\n", in);
	printf("%# +.d\n", in);
	ft_printf("%# +.d\n", in);
	printf("%# +d\n", in);
	ft_printf("%# +d\n", in);
	printf("%#0- +40d\n", in);
	ft_printf("%#0- +40d\n", in);
	printf("%#0 +40d\n", in);
	ft_printf("%#0 +40d\n", in);
	printf("%# +40d\n", in);
	ft_printf("%# +40d\n", in);
	printf("[d char]--------------------------------------------------\n");
	printf("%#0- +40.30hhd\n", ch);
	ft_printf("%#0- +40.30hhd\n", ch);
	printf("%#0 +40.30hhd\n", ch);
	ft_printf("%#0 +40.30hhd\n", ch);
	printf("%#- +40.30hhd\n", ch);
	ft_printf("%#- +40.30hhd\n", ch);
	printf("%# +40.30hhd\n", ch);
	ft_printf("%# +40.30hhd\n", ch);
	printf("%# +.30hhd\n", ch);
	ft_printf("%# +.30hhd\n", ch);
	printf("%# +.hhd\n", ch);
	ft_printf("%# +.hhd\n", ch);
	printf("%# +hhd\n", ch);
	ft_printf("%# +hhd\n", ch);
	printf("%#0- +40hhd\n", ch);
	ft_printf("%#0- +40hhd\n", ch);
	printf("%#0 +40hhd\n", ch);
	ft_printf("%#0 +40hhd\n", ch);
	printf("%# +40hhd\n", ch);
	ft_printf("%# +40hhd\n", ch);
	printf("[d short]------------------------------------------------\n");
	printf("%#0- +40.30hd\n", sh);
	ft_printf("%#0- +40.30hd\n", sh);
	printf("%#0 +40.30hd\n", sh);
	ft_printf("%#0 +40.30hd\n", sh);
	printf("%#- +40.30hd\n", sh);
	ft_printf("%#- +40.30hd\n", sh);
	printf("%# +40.30hd\n", sh);
	ft_printf("%# +40.30hd\n", sh);
	printf("%# +.30hd\n", sh);
	ft_printf("%# +.30hd\n", sh);
	printf("%# +.hd\n", sh);
	ft_printf("%# +.hd\n", sh);
	printf("%# +hd\n", sh);
	ft_printf("%# +hd\n", sh);
	printf("%#0- +40hd\n", sh);
	ft_printf("%#0- +40hd\n", sh);
	printf("%#0 +40hd\n", sh);
	ft_printf("%#0 +40hd\n", sh);
	printf("%# +40hd\n", sh);
	ft_printf("%# +40hd\n", sh);
	printf("[d long]-------------------------------------------------\n");
	printf("%#0- +40.30ld\n", lon);
	ft_printf("%#0- +40.30ld\n", lon);
	printf("%#0 +40.30ld\n", lon);
	ft_printf("%#0 +40.30ld\n", lon);
	printf("%#- +40.30ld\n", lon);
	ft_printf("%#- +40.30ld\n", lon);
	printf("%# +40.30ld\n", lon);
	ft_printf("%# +40.30ld\n", lon);
	printf("%# +.30ld\n", lon);
	ft_printf("%# +.30ld\n", lon);
	printf("%# +.ld\n", lon);
	ft_printf("%# +.ld\n", lon);
	printf("%# +ld\n", lon);
	ft_printf("%# +ld\n", lon);
	printf("%#0- +40ld\n", lon);
	ft_printf("%#0- +40ld\n", lon);
	printf("%#0 +40ld\n", lon);
	ft_printf("%#0 +40ld\n", lon);
	printf("%# +40ld\n", lon);
	ft_printf("%# +40ld\n", lon);
	printf("[d long long]-------------------------------------------\n");
	printf("%#0- +40.30lld\n", lonlon);
	ft_printf("%#0- +40.30lld\n", lonlon);
	printf("%#0 +40.30lld\n", lonlon);
	ft_printf("%#0 +40.30lld\n", lonlon);
	printf("%#- +40.30lld\n", lonlon);
	ft_printf("%#- +40.30lld\n", lonlon);
	printf("%# +40.30lld\n", lonlon);
	ft_printf("%# +40.30lld\n", lonlon);
	printf("%# +.30lld\n", lonlon);
	ft_printf("%# +.30lld\n", lonlon);
	printf("%# +.lld\n", lonlon);
	ft_printf("%# +.lld\n", lonlon);
	printf("%# +lld\n", lonlon);
	ft_printf("%# +lld\n", lonlon);
	printf("%#0- +40lld\n", lonlon);
	ft_printf("%#0- +40lld\n", lonlon);
	printf("%#0 +40lld\n", lonlon);
	ft_printf("%#0 +40lld\n", lonlon);
	printf("%# +40lld\n", lonlon);
	ft_printf("%# +40lld\n", lonlon);
	printf("[u int] --------------------------------------------------\n");
	printf("%#0- +40.30u\n", uin);
	ft_printf("%#0- +40.30u\n", uin);
	printf("%#0 +40.30u\n", uin);
	ft_printf("%#0 +40.30u\n", uin);
	printf("%#- +40.30u\n", uin);
	ft_printf("%#- +40.30u\n", uin);
	printf("%# +.30u\n", uin);
	ft_printf("%# +.30u\n", uin);
	printf("%# +.u\n", uin);
	ft_printf("%# +.u\n", uin);
	printf("%# +u\n", uin);
	ft_printf("%# +u\n", uin);
	printf("%#0- +40u\n", uin);
	ft_printf("%#0- +40u\n", uin);
	printf("%#0 +40u\n", uin);
	ft_printf("%#0 +40u\n", uin);
	printf("%# +40u\n", uin);
	ft_printf("%# +40u\n", uin);
	printf("[u char]--------------------------------------------------\n");
	printf("%#0- +40.30hhu\n", uch);
	ft_printf("%#0- +40.30hhu\n", uch);
	printf("%#0 +40.30hhu\n", uch);
	ft_printf("%#0 +40.30hhu\n", uch);
	printf("%#- +40.30hhu\n", uch);
	ft_printf("%#- +40.30hhu\n", uch);
	printf("%# +40.30hhu\n", uch);
	ft_printf("%# +40.30hhu\n", uch);
	printf("%# +.30hhu\n", uch);
	ft_printf("%# +.30hhu\n", uch);
	printf("%# +.hhu\n", uch);
	ft_printf("%# +.hhu\n", uch);
	printf("%# +hhu\n", uch);
	ft_printf("%# +hhu\n", uch);
	printf("%#0- +40hhu\n", uch);
	ft_printf("%#0- +40hhu\n", uch);
	printf("%#0 +40hhu\n", uch);
	ft_printf("%#0 +40hhu\n", uch);
	printf("%# +40hhu\n", uch);
	ft_printf("%# +40hhu\n", uch);
	printf("[u short]------------------------------------------------\n");
	printf("%#0- +40.30hu\n", ush);
	ft_printf("%#0- +40.30hu\n", ush);
	printf("%#0 +40.30hu\n", ush);
	ft_printf("%#0 +40.30hu\n", ush);
	printf("%#- +40.30hu\n", ush);
	ft_printf("%#- +40.30hu\n", ush);
	printf("%# +40.30hu\n", ush);
	ft_printf("%# +40.30hu\n", ush);
	printf("%# +.30hu\n", ush);
	ft_printf("%# +.30hu\n", ush);
	printf("%# +.hu\n", ush);
	ft_printf("%# +.hu\n", ush);
	printf("%# +hu\n", ush);
	ft_printf("%# +hu\n", ush);
	printf("%#0- +40hu\n", ush);
	ft_printf("%#0- +40hu\n", ush);
	printf("%#0 +40hu\n", ush);
	ft_printf("%#0 +40hu\n", ush);
	printf("%# +40hu\n", ush);
	ft_printf("%# +40hu\n", ush);
	printf("[u long]-------------------------------------------------\n");
	printf("%#0- +40.30lu\n", ulon);
	ft_printf("%#0- +40.30lu\n", ulon);
	printf("%#0 +40.30lu\n", ulon);
	ft_printf("%#0 +40.30lu\n", ulon);
	printf("%#- +40.30lu\n", ulon);
	ft_printf("%#- +40.30lu\n", ulon);
	printf("%# +40.30lu\n", ulon);
	ft_printf("%# +40.30lu\n", ulon);
	printf("%# +.30lu\n", ulon);
	ft_printf("%# +.30lu\n", ulon);
	printf("%# +.lu\n", ulon);
	ft_printf("%# +.lu\n", ulon);
	printf("%# +lu\n", ulon);
	ft_printf("%# +lu\n", ulon);
	printf("%#0- +40lu\n", ulon);
	ft_printf("%#0- +40lu\n", ulon);
	printf("%#0 +40lu\n", ulon);
	ft_printf("%#0 +40lu\n", ulon);
	printf("%# +40lu\n", ulon);
	ft_printf("%# +40lu\n", ulon);
	printf("[u long long]-------------------------------------------\n");
	printf("%#0- +40.30llu\n", ulonlon);
	ft_printf("%#0- +40.30llu\n", ulonlon);
	printf("%#0 +40.30llu\n", ulonlon);
	ft_printf("%#0 +40.30llu\n", ulonlon);
	printf("%#- +40.30llu\n", ulonlon);
	ft_printf("%#- +40.30llu\n", ulonlon);
	printf("%# +40.30llu\n", ulonlon);
	ft_printf("%# +40.30llu\n", ulonlon);
	printf("%# +.30llu\n", ulonlon);
	ft_printf("%# +.30llu\n", ulonlon);
	printf("%# +.llu\n", ulonlon);
	ft_printf("%# +.llu\n", ulonlon);
	printf("%# +llu\n", ulonlon);
	ft_printf("%# +llu\n", ulonlon);
	printf("%#0- +40llu\n", ulonlon);
	ft_printf("%#0- +40llu\n", ulonlon);
	printf("%#0 +40llu\n", ulonlon);
	ft_printf("%#0 +40llu\n", ulonlon);
	printf("%# +40llu\n", ulonlon);
	ft_printf("%# +40llu\n", ulonlon);
	printf("[o int] --------------------------------------------------\n");
	printf("%#0- +40.30o\n", uin);
	ft_printf("%#0- +40.30o\n", uin);
	printf("%#0 +40.30o\n", uin);
	ft_printf("%#0 +40.30o\n", uin);
	printf("%#- +40.30o\n", uin);
	ft_printf("%#- +40.30o\n", uin);
	printf("%# +.30o\n", uin);
	ft_printf("%# +.30o\n", uin);
	printf("%# +.o\n", uin);
	ft_printf("%# +.o\n", uin);
	printf("%# +o\n", uin);
	ft_printf("%# +o\n", uin);
	printf("%#0- +40o\n", uin);
	ft_printf("%#0- +40o\n", uin);
	printf("%#0 +40o\n", uin);
	ft_printf("%#0 +40o\n", uin);
	printf("%# +40o\n", uin);
	ft_printf("%# +40o\n", uin);
	printf("[o char]--------------------------------------------------\n");
	printf("%#0- +40.30hho\n", uch);
	ft_printf("%#0- +40.30hho\n", uch);
	printf("%#0 +40.30hho\n", uch);
	ft_printf("%#0 +40.30hho\n", uch);
	printf("%#- +40.30hho\n", uch);
	ft_printf("%#- +40.30hho\n", uch);
	printf("%# +40.30hho\n", uch);
	ft_printf("%# +40.30hho\n", uch);
	printf("%# +.30hho\n", uch);
	ft_printf("%# +.30hho\n", uch);
	printf("%# +.hho\n", uch);
	ft_printf("%# +.hho\n", uch);
	printf("%# +hho\n", uch);
	ft_printf("%# +hho\n", uch);
	printf("%#0- +40hho\n", uch);
	ft_printf("%#0- +40hho\n", uch);
	printf("%#0 +40hho\n", uch);
	ft_printf("%#0 +40hho\n", uch);
	printf("%# +40hho\n", uch);
	ft_printf("%# +40hho\n", uch);
	printf("[o short]------------------------------------------------\n");
	printf("%#0- +40.30ho\n", ush);
	ft_printf("%#0- +40.30ho\n", ush);
	printf("%#0 +40.30ho\n", ush);
	ft_printf("%#0 +40.30ho\n", ush);
	printf("%#- +40.30ho\n", ush);
	ft_printf("%#- +40.30ho\n", ush);
	printf("%# +40.30ho\n", ush);
	ft_printf("%# +40.30ho\n", ush);
	printf("%# +.30ho\n", ush);
	ft_printf("%# +.30ho\n", ush);
	printf("%# +.ho\n", ush);
	ft_printf("%# +.ho\n", ush);
	printf("%# +ho\n", ush);
	ft_printf("%# +ho\n", ush);
	printf("%#0- +40ho\n", ush);
	ft_printf("%#0- +40ho\n", ush);
	printf("%#0 +40ho\n", ush);
	ft_printf("%#0 +40ho\n", ush);
	printf("%# +40ho\n", ush);
	ft_printf("%# +40ho\n", ush);
	printf("[o long]-------------------------------------------------\n");
	printf("%#0- +40.30lo\n", ulon);
	ft_printf("%#0- +40.30lo\n", ulon);
	printf("%#0 +40.30lo\n", ulon);
	ft_printf("%#0 +40.30lo\n", ulon);
	printf("%#- +40.30lo\n", ulon);
	ft_printf("%#- +40.30lo\n", ulon);
	printf("%# +40.30lo\n", ulon);
	ft_printf("%# +40.30lo\n", ulon);
	printf("%# +.30lo\n", ulon);
	ft_printf("%# +.30lo\n", ulon);
	printf("%# +.lo\n", ulon);
	ft_printf("%# +.lo\n", ulon);
	printf("%# +lo\n", ulon);
	ft_printf("%# +lo\n", ulon);
	printf("%#0- +40lo\n", ulon);
	ft_printf("%#0- +40lo\n", ulon);
	printf("%#0 +40lo\n", ulon);
	ft_printf("%#0 +40lo\n", ulon);
	printf("%# +40lo\n", ulon);
	ft_printf("%# +40lo\n", ulon);
	printf("[o long long]-------------------------------------------\n");
	printf("%#0- +40.30llo\n", ulonlon);
	ft_printf("%#0- +40.30llo\n", ulonlon);
	printf("%#0 +40.30llo\n", ulonlon);
	ft_printf("%#0 +40.30llo\n", ulonlon);
	printf("%#- +40.30llo\n", ulonlon);
	ft_printf("%#- +40.30llo\n", ulonlon);
	printf("%# +40.30llo\n", ulonlon);
	ft_printf("%# +40.30llo\n", ulonlon);
	printf("%# +.30llo\n", ulonlon);
	ft_printf("%# +.30llo\n", ulonlon);
	printf("%# +.llo\n", ulonlon);
	ft_printf("%# +.llo\n", ulonlon);
	printf("%# +llo\n", ulonlon);
	ft_printf("%# +llo\n", ulonlon);
	printf("%#0- +40llo\n", ulonlon);
	ft_printf("%#0- +40llo\n", ulonlon);
	printf("%#0 +40llo\n", ulonlon);
	ft_printf("%#0 +40llo\n", ulonlon);
	printf("%# +40llo\n", ulonlon);
	ft_printf("%# +40llo\n", ulonlon);
	printf("[x X int] --------------------------------------------------\n");
	printf("%#0- +40.30x\n", uin);
	ft_printf("%#0- +40.30x\n", uin);
	printf("%#0 +40.30X\n", uin);
	ft_printf("%#0 +40.30X\n", uin);
	printf("%#- +40.30x\n", uin);
	ft_printf("%#- +40.30x\n", uin);
	printf("%# +.30X\n", uin);
	ft_printf("%# +.30X\n", uin);
	printf("%# +.x\n", uin);
	ft_printf("%# +.x\n", uin);
	printf("%# +X\n", uin);
	ft_printf("%# +X\n", uin);
	printf("%#0- +40x\n", uin);
	ft_printf("%#0- +40x\n", uin);
	printf("%#0 +40X\n", uin);
	ft_printf("%#0 +40X\n", uin);
	printf("%# +40x\n", uin);
	ft_printf("%# +40x\n", uin);
	printf("[x X char]--------------------------------------------------\n");
	printf("%#0- +40.30hhX\n", uch);
	ft_printf("%#0- +40.30hhX\n", uch);
	printf("%#0 +40.30hhx\n", uch);
	ft_printf("%#0 +40.30hhx\n", uch);
	printf("%#- +40.30hhX\n", uch);
	ft_printf("%#- +40.30hhX\n", uch);
	printf("%# +40.30hhx\n", uch);
	ft_printf("%# +40.30hhx\n", uch);
	printf("%# +.30hhX\n", uch);
	ft_printf("%# +.30hhX\n", uch);
	printf("%# +.hhx\n", uch);
	ft_printf("%# +.hhx\n", uch);
	printf("%# +hhX\n", uch);
	ft_printf("%# +hhX\n", uch);
	printf("%#0- +40hhx\n", uch);
	ft_printf("%#0- +40hhx\n", uch);
	printf("%#0 +40hhX\n", uch);
	ft_printf("%#0 +40hhX\n", uch);
	printf("%# +40hhx\n", uch);
	ft_printf("%# +40hhx\n", uch);
	printf("[x X short]------------------------------------------------\n");
	printf("%#0- +40.30hx\n", ush);
	ft_printf("%#0- +40.30hx\n", ush);
	printf("%#0 +40.30hX\n", ush);
	ft_printf("%#0 +40.30hX\n", ush);
	printf("%#- +40.30hx\n", ush);
	ft_printf("%#- +40.30hx\n", ush);
	printf("%# +40.30hX\n", ush);
	ft_printf("%# +40.30hX\n", ush);
	printf("%# +.30hx\n", ush);
	ft_printf("%# +.30hx\n", ush);
	printf("%# +.hX\n", ush);
	ft_printf("%# +.hX\n", ush);
	printf("%# +hx\n", ush);
	ft_printf("%# +hx\n", ush);
	printf("%#0- +40hX\n", ush);
	ft_printf("%#0- +40hX\n", ush);
	printf("%#0 +40hx\n", ush);
	ft_printf("%#0 +40hx\n", ush);
	printf("%# +40hX\n", ush);
	ft_printf("%# +40hX\n", ush);
	printf("[x X long]-------------------------------------------------\n");
	printf("%#0- +40.30lX\n", ulon);
	ft_printf("%#0- +40.30lX\n", ulon);
	printf("%#0 +40.30lx\n", ulon);
	ft_printf("%#0 +40.30lx\n", ulon);
	printf("%#- +40.30lX\n", ulon);
	ft_printf("%#- +40.30lX\n", ulon);
	printf("%# +40.30lx\n", ulon);
	ft_printf("%# +40.30lx\n", ulon);
	printf("%# +.30lX\n", ulon);
	ft_printf("%# +.30lX\n", ulon);
	printf("%# +.lx\n", ulon);
	ft_printf("%# +.lx\n", ulon);
	printf("%# +lX\n", ulon);
	ft_printf("%# +lX\n", ulon);
	printf("%#0- +40lx\n", ulon);
	ft_printf("%#0- +40lx\n", ulon);
	printf("%#0 +40lX\n", ulon);
	ft_printf("%#0 +40lX\n", ulon);
	printf("%# +40lx\n", ulon);
	ft_printf("%# +40lx\n", ulon);
	printf("[x X long long]-------------------------------------------\n");
	printf("%#0- +40.30llx\n", ulonlon);
	ft_printf("%#0- +40.30llx\n", ulonlon);
	printf("%#0 +40.30llX\n", ulonlon);
	ft_printf("%#0 +40.30llX\n", ulonlon);
	printf("%#- +40.30llx\n", ulonlon);
	ft_printf("%#- +40.30llx\n", ulonlon);
	printf("%# +40.30llX\n", ulonlon);
	ft_printf("%# +40.30llX\n", ulonlon);
	printf("%# +.30llx\n", ulonlon);
	ft_printf("%# +.30llx\n", ulonlon);
	printf("%# +.llX\n", ulonlon);
	ft_printf("%# +.llX\n", ulonlon);
	printf("%# +llx\n", ulonlon);
	ft_printf("%# +llx\n", ulonlon);
	printf("%#0- +40llX\n", ulonlon);
	ft_printf("%#0- +40llX\n", ulonlon);
	printf("%#0 +40llx\n", ulonlon);
	ft_printf("%#0 +40llx\n", ulonlon);
	printf("%# +40llX\n", ulonlon);
	ft_printf("%# +40llX\n", ulonlon);
	printf("[c] --------------------------------------------------\n");
	printf("%#0- +40.30c\n", 35);
	ft_printf("%#0- +40.30c\n", 35);
	printf("%#0 +40.30c\n", 'a');
	ft_printf("%#0 +40.30c\n", 'a');
	printf("%#- +40.30c\n", 'l');
	ft_printf("%#- +40.30c\n", 'l');
	printf("%# +.30c\n", 106);
	ft_printf("%# +.30c\n", 106);
	printf("%# +.c\n", 's');
	ft_printf("%# +.c\n", 's');
	printf("%# +c\n", 113);
	ft_printf("%# +c\n", 113);
	printf("%#0- +40c\n", 125);
	ft_printf("%#0- +40c\n", 125);
	printf("%#0 +40c\n", 93);
	ft_printf("%#0 +40c\n", 93);
	printf("%# +40c\n", '%');
	ft_printf("%# +40c\n", '%');
	printf("[s] --------------------------------------------------\n");
	printf("%#0- +40.30s\n", "hello");
	ft_printf("%#0- +40.30s\n", "hello");
	printf("%#0 +40.30s\n", "world");
	ft_printf("%#0 +40.30s\n", "world");
	printf("%#- +40.30s\n", "earth");
	ft_printf("%#- +40.30s\n", "earth");
	printf("%# +.30s\n", "mars");
	ft_printf("%# +.30s\n", "mars");
	printf("%# +.s\n", "venus");
	ft_printf("%# +.s\n", "venus");
	printf("%#0 +20.s\n", "venus");
	ft_printf("%#0 +20.s\n", "venus");
	printf("%# +s\n", "jupiter");
	ft_printf("%# +s\n", "jupiter");
	printf("%#0- +40s\n", "sun");
	ft_printf("%#0- +40s\n", "sun");
	printf("%#0 +40s\n", "pluto");
	ft_printf("%#0 +40s\n", "pluto");
	printf("%# +40s\n", "saturn");
	ft_printf("%# +40s\n", "saturn");
	printf("%# +.3s\n", "saturn");
	ft_printf("%# +.3s\n", "saturn");
	printf("%# +.6s\n", "saturn");
	ft_printf("%# +.6s\n", "saturn");
	printf("%# +.5s\n", "saturn");
	ft_printf("%# +.5s\n", "saturn");
	printf("[p] --------------------------------------------------\n");
	printf("%#0- +40.30p\n", p);
	ft_printf("%#0- +40.30p\n", p);
	printf("%#0 +40.30p\n", p1);
	ft_printf("%#0 +40.30p\n", p1);
	printf("%#- +40.30p\n", p);
	ft_printf("%#- +40.30p\n", p);
	printf("%# +.30p\n", p1);
	ft_printf("%# +.30p\n", p1);
	printf("%# +.p\n", p);
	ft_printf("%# +.p\n", p);
	printf("%#0 +20.p\n", p1);
	ft_printf("%#0 +20.p\n", p1);
	printf("%# +p\n", p);
	ft_printf("%# +p\n", p);
	printf("%#0- +40p\n", p1);
	ft_printf("%#0- +40p\n", p1);
	printf("%#0 +40p\n", p);
	ft_printf("%#0 +40p\n", p);
	printf("%# +40p\n", p1);
	ft_printf("%# +40p\n", p1);
	printf("%# +.3p\n", p);
	ft_printf("%# +.3p\n", p);
	printf("%# +.6p\n", p1);
	ft_printf("%# +.6p\n", p1);
	printf("%# +.5p\n", p);
	ft_printf("%# +.5p\n", p);
	printf("[%%] --------------------------------------------------\n");
	printf("%#0- +40.30%\n");
	ft_printf("%#0- +40.30%\n");
	printf("%#0 +40.30%\n");
	ft_printf("%#0 +40.30%\n");
	printf("%#- +40.30%\n");
	ft_printf("%#- +40.30%\n");
	printf("%# +.30%\n");
	ft_printf("%# +.30%\n");
	printf("%# +.%\n");
	ft_printf("%# +.%\n");
	printf("%#0 +20.%\n");
	ft_printf("%#0 +20.%\n");
	printf("%# +%\n");
	ft_printf("%# +%\n");
	printf("%#0- +40%\n");
	ft_printf("%#0- +40%\n");
	printf("%#0 +40%\n");
	ft_printf("%#0 +40%\n");
	printf("%# +40%\n");
	ft_printf("%# +40%\n");
	printf("%# +.3%\n");
	ft_printf("%# +.3%\n");
	printf("%# +.6%\n");
	ft_printf("%# +.6%\n");
	printf("%# +.5%\n");
	ft_printf("%# +.5%\n");
	printf("[f float] --------------------------------------------------\n");
//	printf("%#0- +30.20lllhhhLlLhhhlll.20+30 -0#fcsphola\n", 3.1416);
//	ft_printf("%#0- +30.20lllhhhLlLhhhlll.20+30 -0#fcsphola\n", 3.1416);
	printf("%#0- +40.20f\n", 0.1234);
	ft_printf("%#0- +40.20Lf\n", 0.1234);
	printf("%#0 +40.30f\n", 0.1234);
//	ft_printf("%#0 +40.30f\n", 0.1234);
	printf("%#- +40.30f\n", 0.1234);
//	ft_printf("%#- +40.30f\n", 0.1234);
	printf("%# +.30f\n", 0.1234);
//	ft_printf("%# +.30f\n", 0.1234);
	printf("%# +.f\n", 0.1416);
//	ft_printf("%# +.f\n", 0.1416);
	printf("%# +f\n", 0.5678);
//	ft_printf("%# +f\n", 0.5678);
	printf("%#0- +40f\n", 0.5678);
//	ft_printf("%#0- +40f\n", 0.5678);
	printf("%#0 +40f\n", 0.5678);
//	ft_printf("%#0 +40f\n", 0.5678);
	printf("%# +40f\n", 0.5678);
//	ft_printf("%# +40f\n", 0.5678);
	printf("%f\n", 3.1416);
//	ft_printf("%f\n", 3.1416);
	printf("%.2f\n", 3.1416);
//	ft_printf("%.2f\n", 3.1416);
	printf("%.f\n", 3.1416);
//	ft_printf("%.f\n", 3.1416);
	printf("%f\n", -3.1416);
//	ft_printf("%f\n", -3.1416);
	printf("%010.2f\n", -3.1416);
//	ft_printf("%010.2f\n", -3.1416);
	printf("%-10.2f\n", -3.1416);
//	ft_printf("%-10.2f\n", -3.1416);
	printf("%-+10.2f\n", -3.1416);
//	ft_printf("%-+10.2f\n", -3.1416);
	printf("%-+10.2f\n", 3.1416);
//	ft_printf("%-+10.2f\n", 3.1416);
	printf("%- 10.2f\n", 3.1416);
//	ft_printf("%- 10.2f\n", 3.1416);
	printf("%- 10.2f\n", -3.1416);
//	ft_printf("%- 10.2f\n", -3.1416);
	printf("%#- 10.f\n", 3.1416);
//	ft_printf("%#- 10.f\n", 3.1416);
	printf("%.9f\n", 3.141631416);
//	ft_printf("%.9f\n", 3.141631416);
	printf("%.9lf\n", (double) 3.141631416);
//	ft_printf("%.9lf\n", (double) 3.141631416);
	printf("%.9Lf\n", (long double) 3.1416);
//	ft_printf("%.9Lf\n", (long double) 3.1416);
	printf("%f\n", 31.416);
//	ft_printf("%f\n", 31.416);
	printf("%f\n", 314.16);
//	ft_printf("%f\n", 314.16);
	printf("%f\n", 3141.6);
//	ft_printf("%f\n", 3141.6);
	printf("%#.f\n", 3.1);
//	ft_printf("%#.f\n", 3.1);
	printf("%0f\n", 3.1416);
//	ft_printf("%0f\n", 3.1416);
	printf("%-f\n", 3.1416);
//	ft_printf("%-f\n", 3.1416);
	printf("% f\n", 3.1416);
//	ft_printf("% f\n", 3.1416);
	printf("%+f\n", 3.1416);
//	ft_printf("%+f\n", 3.1416);
	printf("%20f\n", 3.1416);
//	ft_printf("%20f\n", 3.1416);
	printf("%.20f\n", 3.1416);
//	ft_printf("%.20f\n", 3.1416);
	
	system("leaks a.out");
	return (0);
}
